---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-configuraion
  namespace: flux-system
spec:
  dependsOn:
      - name: metallb-crds
      - name: metallb
  path: ./clusters/home-prod-1/configuration/infrastructure/metallb
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 10m
  prune: true
  wait: true